version: '3'
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    environment:
      TYPEORM_HOST: postgres
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: Almog
      TYPEORM_PASSWORD: Almog2121
      TYPEORM_DATABASE: taskmanagement
      TYPEORM_SYNCHRONIZE: true
      TYPEORM_LOGGING: true
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    command: npm run start:dev

  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: taskmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Almog2121
